FROM mitmproxy/mitmproxy:10.4.2

WORKDIR /work

COPY requirements.txt /work/requirements.txt
RUN pip install --no-cache-dir -r /work/requirements.txt

CMD ["mitmdump", "-s", "/work/mitmproxy.py", "--listen-host", "0.0.0.0", "--listen-port", "8080"]
